# Generated by Django 3.1.1 on 2020-09-21 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destination2',
            fields=[
                ('destination_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.destination')),
                ('tag1', models.CharField(max_length=100)),
                ('tag2', models.CharField(max_length=100)),
                ('tag3', models.CharField(max_length=100)),
                ('tag4', models.CharField(max_length=100)),
                ('tag5', models.CharField(max_length=100)),
                ('tag6', models.CharField(max_length=100)),
            ],
            bases=('home.destination',),
        ),
    ]
