# Generated by Django 3.1.1 on 2020-09-21 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_destination2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag1', models.CharField(max_length=100)),
                ('tag2', models.CharField(max_length=100)),
                ('tag3', models.CharField(max_length=100)),
                ('tag4', models.CharField(max_length=100)),
                ('tag5', models.CharField(max_length=100)),
                ('tag6', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Destination2',
        ),
    ]
