# Generated by Django 3.1.1 on 2020-09-30 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20200921_1341'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
